# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:lts

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: echo 'start'
      - run: yarn install
      - run: pwd
      - run: node ./build/cli.js
      - run: yarn run build
      - run: git config --global user.email "linus.wang.i77@qq.com"
      - run: git config --global user.name "Linus Wang"
      - run: git checkout master
      - run: git add .
      - run: git commit -m "Update From Circle CI"
      - run: git push https://$GITHUB_LOGIN:$GITHUB_PASSWORD@github.com/okfe/okfe.github.io.git
      - run: echo 'done'
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  schedule-workflow:
    triggers: #use the triggers key to indicate a scheduled build
      - schedule:
          cron: "0 12 * * *" # use cron syntax to set the schedule
          filters:
            branches:
              only:
                - master
    jobs:
      - build
